---
# handlers file for roles/vector
- name: Restart vector service
  ansible.builtin.service:
    name: vector
    state: restarted
    enabled: true


- name: Flush handlers
  ansible.builtin.meta: flush_handlers